env: "consensus"

env_args:
  n_agents: 3
  map_name: 'consensus_3'

test_greedy: True
test_nepisode: 32
test_interval: 10
log_interval: 10
runner_log_interval: 10
learner_log_interval: 10
obs_agent_id: True